#!/usr/bin/env bash
# context-monitor.sh — UserPromptSubmit hook: warn (or block) when context nears limit.
#
# Reads a UserPromptSubmit event JSON from stdin. Compares transcript_token_count
# to the configured threshold. Behavior depends on mode:
#
#   remind-once   — exits 0, single stderr line (advisory; no state tracking in v1)
#   remind-until  — exits 0, stderr line every turn over threshold
#   auto          — writes a handoff file and exits 2 (blocking) to surface the message
#
# Config location: $MEMO_FLOW_CONFIG (env) or ./.claude/memo-flow/config.json (cwd)
# Config key: "context-monitor"
# Fail-open: missing or unparseable config → treat as enabled with defaults.
# Disabled hook: exits 0 immediately with no output.

set -euo pipefail

# ── find config ───────────────────────────────────────────────────────────────

CONFIG_FILE="${MEMO_FLOW_CONFIG:-./.claude/memo-flow/config.json}"

# ── read config (fail-open) ───────────────────────────────────────────────────

read_config() {
  python3 - "$CONFIG_FILE" <<'PYEOF'
import json, os, sys

config_file = sys.argv[1]
defaults = {
    "enabled": True,
    "threshold": 99000,
    "mode": "auto",
    "handoff_dir": None,
}

if not os.path.exists(config_file):
    print(json.dumps(defaults))
    sys.exit(0)

try:
    data = json.load(open(config_file))
    hook_cfg = data.get("context-monitor", {})
    if not isinstance(hook_cfg, dict):
        print(json.dumps(defaults))
        sys.exit(0)
    merged = dict(defaults)
    merged.update(hook_cfg)
    print(json.dumps(merged))
except Exception:
    print(json.dumps(defaults))
PYEOF
}

config_json=$(read_config)

enabled=$(python3 -c "import json,sys; print(json.loads(sys.argv[1]).get('enabled', True))" "$config_json")

# disabled → exit 0 immediately (no latency cost)
if [ "$enabled" = "False" ]; then
  exit 0
fi

threshold=$(python3 -c "import json,sys; print(json.loads(sys.argv[1]).get('threshold', 99000))" "$config_json")
mode=$(python3 -c "import json,sys; print(json.loads(sys.argv[1]).get('mode', 'auto'))" "$config_json")
handoff_dir=$(python3 -c "
import json, sys, os
cfg = json.loads(sys.argv[1])
d = cfg.get('handoff_dir')
if d:
    print(os.path.expanduser(str(d)))
else:
    print(os.path.expanduser('~/.claude/memo-flow/handoffs'))
" "$config_json")

# ── read event from stdin ─────────────────────────────────────────────────────

event=$(cat)

token_count=$(python3 -c "
import json, sys
try:
    data = json.loads(sys.argv[1])
    print(int(data.get('transcript_token_count', 0)))
except Exception:
    print(0)
" "$event")

# ── below threshold → silent pass ─────────────────────────────────────────────

if [ "$token_count" -lt "$threshold" ] 2>/dev/null; then
  exit 0
fi

# ── above threshold: dispatch by mode ─────────────────────────────────────────

reminder_msg="context-monitor: ~${token_count} tokens — near limit (${threshold}). Run /handoff before reasoning degrades."

case "$mode" in

  remind-once|remind-until)
    echo "$reminder_msg" >&2
    exit 0
    ;;

  auto)
    # write a handoff document
    mkdir -p "$handoff_dir"
    handoff_file="$handoff_dir/handoff-$(date +%Y%m%d-%H%M%S)-$$.md"
    cat > "$handoff_file" <<HANDOFF_EOF
# Context Handoff

Generated by context-monitor at $(date -u +"%Y-%m-%dT%H:%M:%SZ").

Token count at trigger: ${token_count} (threshold: ${threshold})

## Resume note

Context window is near capacity. Start a fresh session and re-read Memory before continuing.

HANDOFF_EOF

    # exit 2 surfaces the message and blocks the prompt
    echo "$reminder_msg" >&2
    echo "Handoff written: $handoff_file" >&2
    exit 2
    ;;

  *)
    # unknown mode — advisory only
    echo "$reminder_msg" >&2
    exit 0
    ;;

esac
